name: tribe9
favicon: null
layout_spectrum: 0.9429977631662041
typography_spectrum: 0.379565900657326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7691045517567545
  lightness: 0.049613382667303085
  saturation: 0.6136108112987131
  rhythmicContrast: 0.2520218207500875
purpose: []
